// Generated by row_row_row tool
// Auto-generated file. Do not modify.
import 'package:supabase_flutter/supabase_flutter.dart';
class FavouriteKeywordRow {
  static const table = 'favourite_keyword';

  static const field = (
    userId: 'user_id',
    keywordId: 'keyword_id',
  );

  final String userId;
  final int keywordId;

  const FavouriteKeywordRow({
    required this.userId,
    required this.keywordId,
  });

  factory FavouriteKeywordRow.fromJson(Map<String, dynamic> json) {
    return FavouriteKeywordRow(
      userId: json[field.userId] as String,
      keywordId: (json[field.keywordId] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.userId: userId,
      field.keywordId: keywordId,
    };
  }

  FavouriteKeywordRow copyWith({
    String? userId,
    int? keywordId,
  }) {
    return FavouriteKeywordRow(
      userId: userId ?? this.userId,
      keywordId: keywordId ?? this.keywordId,
    );
  }

  /// Creates a new row in the database.
  /// 
  /// Only non-null fields will be included in the insert payload.
  /// Primary keys and auto-generated fields can be set manually or left null for database defaults.
  /// Returns the created row with any auto-generated values.
  /// 
  /// Requires [supabase_flutter] package to be installed and initialized.
  /// Fetches a single row from the database by its primary key.
  /// 
  /// Returns the row if found, or throws an error if not found.
  /// 
  /// Requires [supabase_flutter] package to be installed and initialized.
  static Future<FavouriteKeywordRow> create({
    String? userId,
    int? keywordId,
  }) async {
    // Build the insert payload with only non-null fields using collection if
    final Map<String, dynamic> insertPayload = {
      if (userId != null) field.userId: userId,
      if (keywordId != null) field.keywordId: keywordId,
    };

    final response = await Supabase.instance.client
        .from(table)
        .insert(insertPayload)
        .select()
        .single();
    return FavouriteKeywordRow.fromJson(response);
  }

  /// Fetches a single row from the database by its primary key.
  /// 
  /// Returns the row if found, or throws an error if not found.
  /// 
  /// Requires [supabase_flutter] package to be installed and initialized.
  static Future<FavouriteKeywordRow> getFromUserIdKeywordId(String userId, int keywordId) async {
    final response = await Supabase.instance.client
        .from(table)
        .select()
        .eq(field.userId, userId)
        .eq(field.keywordId, keywordId)
        .single();
    return FavouriteKeywordRow.fromJson(response);
  }
}
