// Generated by row_row_row tool
// Auto-generated file. Do not modify.
import 'package:supabase_flutter/supabase_flutter.dart';

class FavouriteTopicRow {
  static const table = 'favourite_topic';

  static const field = (topicId: 'topic_id', userId: 'user_id');

  final int topicId;
  final String userId;

  const FavouriteTopicRow({required this.topicId, required this.userId});

  factory FavouriteTopicRow.fromJson(Map<String, dynamic> json) {
    return FavouriteTopicRow(
      topicId: (json[field.topicId] as num).toInt(),
      userId: json[field.userId] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {field.topicId: topicId, field.userId: userId};
  }

  FavouriteTopicRow copyWith({int? topicId, String? userId}) {
    return FavouriteTopicRow(
      topicId: topicId ?? this.topicId,
      userId: userId ?? this.userId,
    );
  }

  /// Creates a new row in the database.
  ///
  /// Only non-null fields will be included in the insert payload.
  /// Primary keys and auto-generated fields can be set manually or left null for database defaults.
  /// Returns the created row with any auto-generated values.
  ///
  /// Requires [supabase_flutter] package to be installed and initialized.
  /// Fetches a single row from the database by its primary key.
  ///
  /// Returns the row if found, or throws an error if not found.
  ///
  /// Requires [supabase_flutter] package to be installed and initialized.
  static Future<FavouriteTopicRow> create({
    int? topicId,
    String? userId,
  }) async {
    // Build the insert payload with only non-null fields using collection if
    final Map<String, dynamic> insertPayload = {
      if (topicId != null) field.topicId: topicId,
      if (userId != null) field.userId: userId,
    };

    final response =
        await Supabase.instance.client
            .from(table)
            .insert(insertPayload)
            .select()
            .single();
    return FavouriteTopicRow.fromJson(response);
  }

  /// Fetches a single row from the database by its primary key.
  ///
  /// Returns the row if found, or throws an error if not found.
  ///
  /// Requires [supabase_flutter] package to be installed and initialized.
  static Future<FavouriteTopicRow> getFromTopicIdUserId(
    int topicId,
    String userId,
  ) async {
    final response =
        await Supabase.instance.client
            .from(table)
            .select()
            .eq(field.topicId, topicId)
            .eq(field.userId, userId)
            .single();
    return FavouriteTopicRow.fromJson(response);
  }
}
