// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ArticleRow {
  static const field = (
    articleId: 'article_id',
    title: 'title',
    link: 'link',
    imageUrl: 'image_url',
    description: 'description',
    pubDate: 'pub_date',
    rssId: 'rss_id',
  );

  final int articleId;
  final dynamic title;
  final dynamic? link;
  final dynamic? imageUrl;
  final dynamic? description;
  final DateTime? pubDate;
  final int? rssId;

  const ArticleRow({
    required this.articleId,
    required this.title,
    this.link,
    this.imageUrl,
    this.description,
    this.pubDate,
    this.rssId,
  });

  factory ArticleRow.fromJson(Map<String, dynamic> json) {
    return ArticleRow(
      articleId: (json[field.articleId] as num).toInt(),
      title: json[field.title],
      link: json[field.link],
      imageUrl: json[field.imageUrl],
      description: json[field.description],
      pubDate:
          json[field.pubDate] == null
              ? null
              : DateTime.tryParse(json[field.pubDate] ?? ''),
      rssId:
          json[field.rssId] == null
              ? null
              : (json[field.rssId] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.articleId: articleId,
      field.title: title,
      field.link: link,
      field.imageUrl: imageUrl,
      field.description: description,
      field.pubDate: pubDate?.toIso8601String(),
      field.rssId: rssId,
    };
  }
}
