// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ArticleKeywordRow {
  static const field = (keywordId: 'keyword_id', articleId: 'article_id');

  final int keywordId;
  final int articleId;

  const ArticleKeywordRow({required this.keywordId, required this.articleId});

  factory ArticleKeywordRow.fromJson(Map<String, dynamic> json) {
    return ArticleKeywordRow(
      keywordId: (json[field.keywordId] as num).toInt(),
      articleId: (json[field.articleId] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {field.keywordId: keywordId, field.articleId: articleId};
  }
}
