// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class FavouriteTopicRow {
  static const field = (topicId: 'topic_id', userId: 'user_id');

  final int topicId;
  final String userId;

  const FavouriteTopicRow({required this.topicId, required this.userId});

  factory FavouriteTopicRow.fromJson(Map<String, dynamic> json) {
    return FavouriteTopicRow(
      topicId: (json[field.topicId] as num).toInt(),
      userId: json[field.userId] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {field.topicId: topicId, field.userId: userId};
  }
}
