// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class FavouriteArticleRow {
  static const field = (articleId: 'article_id', userId: 'user_id');

  final int articleId;
  final String userId;

  const FavouriteArticleRow({required this.articleId, required this.userId});

  factory FavouriteArticleRow.fromJson(Map<String, dynamic> json) {
    return FavouriteArticleRow(
      articleId: (json[field.articleId] as num).toInt(),
      userId: json[field.userId] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {field.articleId: articleId, field.userId: userId};
  }
}
