// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class HistoryRow {
  static const field = (
    historyId: 'history_id',
    userId: 'user_id',
    articleId: 'article_id',
    numberOfArticleView: 'number_of_article_view',
    maximumReadTime: 'maximum_read_time',
    averageReadTime: 'average_read_time',
    percentageScrolled: 'percentage_scrolled',
  );

  final int historyId;
  final String userId;
  final int? articleId;
  final dynamic? numberOfArticleView;
  final dynamic? maximumReadTime;
  final dynamic? averageReadTime;
  final dynamic? percentageScrolled;

  const HistoryRow({
    required this.historyId,
    required this.userId,
    this.articleId,
    this.numberOfArticleView,
    this.maximumReadTime,
    this.averageReadTime,
    this.percentageScrolled,
  });

  factory HistoryRow.fromJson(Map<String, dynamic> json) {
    return HistoryRow(
      historyId: (json[field.historyId] as num).toInt(),
      userId: json[field.userId] as String,
      articleId:
          json[field.articleId] == null
              ? null
              : (json[field.articleId] as num?)?.toInt(),
      numberOfArticleView: json[field.numberOfArticleView],
      maximumReadTime: json[field.maximumReadTime],
      averageReadTime: json[field.averageReadTime],
      percentageScrolled: json[field.percentageScrolled],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.historyId: historyId,
      field.userId: userId,
      field.articleId: articleId,
      field.numberOfArticleView: numberOfArticleView,
      field.maximumReadTime: maximumReadTime,
      field.averageReadTime: averageReadTime,
      field.percentageScrolled: percentageScrolled,
    };
  }
}
