// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class KeywordRow {
  static const field = (keywordId: 'keyword_id', keywordName: 'keyword_name');

  final int keywordId;
  final dynamic keywordName;

  const KeywordRow({required this.keywordId, required this.keywordName});

  factory KeywordRow.fromJson(Map<String, dynamic> json) {
    return KeywordRow(
      keywordId: (json[field.keywordId] as num).toInt(),
      keywordName: json[field.keywordName],
    );
  }

  Map<String, dynamic> toJson() {
    return {field.keywordId: keywordId, field.keywordName: keywordName};
  }
}
