// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class NewspaperRow {
  static const field = (
    newspaperId: 'newspaper_id',
    newspaperName: 'newspaper_name',
    newspaperImage: 'newspaper_image',
  );

  final int newspaperId;
  final dynamic newspaperName;
  final dynamic? newspaperImage;

  const NewspaperRow({
    required this.newspaperId,
    required this.newspaperName,
    this.newspaperImage,
  });

  factory NewspaperRow.fromJson(Map<String, dynamic> json) {
    return NewspaperRow(
      newspaperId: (json[field.newspaperId] as num).toInt(),
      newspaperName: json[field.newspaperName],
      newspaperImage: json[field.newspaperImage],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.newspaperId: newspaperId,
      field.newspaperName: newspaperName,
      field.newspaperImage: newspaperImage,
    };
  }
}
