// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class RssRow {
  static const field = (
    id: 'id',
    rssLink: 'rss_link',
    newspaperId: 'newspaper_id',
    topicId: 'topic_id',
  );

  final int id;
  final String? rssLink;
  final int? newspaperId;
  final int? topicId;

  const RssRow({
    required this.id,
    this.rssLink,
    this.newspaperId,
    this.topicId,
  });

  factory RssRow.fromJson(Map<String, dynamic> json) {
    return RssRow(
      id: (json[field.id] as num).toInt(),
      rssLink: json[field.rssLink],
      newspaperId:
          json[field.newspaperId] == null
              ? null
              : (json[field.newspaperId] as num?)?.toInt(),
      topicId:
          json[field.topicId] == null
              ? null
              : (json[field.topicId] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.rssLink: rssLink,
      field.newspaperId: newspaperId,
      field.topicId: topicId,
    };
  }
}
