// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TopicRow {
  static const field = (topicId: 'topic_id', topicName: 'topic_name');

  final int topicId;
  final dynamic topicName;

  const TopicRow({required this.topicId, required this.topicName});

  factory TopicRow.fromJson(Map<String, dynamic> json) {
    return TopicRow(
      topicId: (json[field.topicId] as num).toInt(),
      topicName: json[field.topicName],
    );
  }

  Map<String, dynamic> toJson() {
    return {field.topicId: topicId, field.topicName: topicName};
  }
}
