// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class UsersRow {
  static const field = (
    userId: 'user_id',
    fullName: 'full_name',
    avatarUrl: 'avatar_url',
    createdAt: 'created_at',
    themeMode: 'theme_mode',
    themeColor: 'theme_color',
  );

  final String userId;
  final String? fullName;
  final String? avatarUrl;
  final DateTime? createdAt;
  final dynamic? themeMode;
  final dynamic? themeColor;

  const UsersRow({
    required this.userId,
    this.fullName,
    this.avatarUrl,
    this.createdAt,
    this.themeMode,
    this.themeColor,
  });

  factory UsersRow.fromJson(Map<String, dynamic> json) {
    return UsersRow(
      userId: json[field.userId] as String,
      fullName: json[field.fullName],
      avatarUrl: json[field.avatarUrl],
      createdAt:
          json[field.createdAt] == null
              ? null
              : DateTime.tryParse(json[field.createdAt] ?? ''),
      themeMode: json[field.themeMode],
      themeColor: json[field.themeColor],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      field.userId: userId,
      field.fullName: fullName,
      field.avatarUrl: avatarUrl,
      field.createdAt: createdAt?.toIso8601String(),
      field.themeMode: themeMode,
      field.themeColor: themeColor,
    };
  }
}
